project:
  type: website

website:
  title: "Aadarsh Agarwal"
  description: "Technical notes by Aadarsh Agarwal."
  site-url: https://www.aadarwal.com/blog/
  repo-url: https://github.com/aadarwal-training-data/blog
  navbar:
    title: false

format:
  html:
    theme: [default, theme.scss]
    html-math-method: katex
    smooth-scroll: true
    include-in-header: _redirect.html
